---
archweb_db_host: "{{ hostvars['archlinux.org']['wireguard_address'] }}"
acme_challenge_zone: "acme-challenge.archlinux.org"

# raise tcp window limits to 32MiB
tcp_rmem: "10240 87380 33554432"
tcp_wmem: "10240 87380 33554432"
